namespace LivingWorld.Core;

public enum WorldEventKind
{
    SettlementCreated,
    CitizenCreated,
    CitizenImported,
    ArmyCreated,
    OwnershipAssigned,
    OwnershipTransferred,
    ResourceAdded,
    ResourceConsumed,
    FoodShortage,
    CitizenAged,
    CitizenBorn,
    RaidLaunched,
    IntelReported,
    RaidOpportunityCreated,
    RaidOpportunityConsumed,
    RaidIntelFactRecorded,
    RaidPreparationCreated,
    RaidPreparationReleased,
    RaidPreparationLaunched,
    MaterializationLeaseCreated,
    MaterializationLeasePawnBound,
    MaterializationLeaseResolved,
    SettlementIntelUpdated,
    RaidPawnBound,
    CitizenDied,
    RefugeeCreated,
    MigrationStarted,
    MigrationCompleted,
    RaidPawnReturned,
    RaidPawnCaptured,
    RaidPawnMissing,
    PrisonerCaptured,
    PrisonerRecruited,
    PrisonerEnslaved,
    PrisonerReleased,
    PrisonerEscaped,
    RaidResolved,
    DrifterArrived,
    DrifterAssimilated,
    DrifterReservoirReplenished,
    SettlementFounded,
    FactionCollapsed,
    SettlementProductionUpdated,
    SettlementTradeRecorded,
    DrifterMaterialized,
    WarbandLaunched,
    SettlementCaptured,
    DiplomaticMissionSent,
    SettlementDeveloped,
    CaravanLaunched,
    CaravanArrived,
    CaravanDestroyed,
    SettlementProjectStarted,
    SettlementProjectCompleted,
    SettlementFacilityBuilt,
    SettlementFacilityDamaged,
    SettlementFacilityRepaired,
    SettlementDestroyed,
    SettlementAbandoned,
    SettlementRelocationStarted,
    RuinReclaimed,
    RuinPruned,
    ConflictStarted,
    ConflictUpdated,
    ConflictClaimRecorded,
    ConflictTruceStarted,
    WarRefugeesRecorded,
    AnimalCohortCreated,
    AnimalCohortGrew,
    AnimalCohortDeclined,
    AnimalCohortMigrated,
    AnimalProductsHarvested,
    AnimalHunted,
    AnimalBreedingProjectStarted,
    AnimalBreedingProjectCompleted,
    AnimalCohortIncubated,
    CropStrainProjectStarted,
    CropStrainProjectCompleted,
    TechnologyDiffused,
    WorldMissionDisrupted
}

public sealed record WorldEvent(
    EntityId Id,
    WorldEventKind Kind,
    int Tick,
    EntityId? SubjectId,
    string Summary);
